### ISSUE TITLE
#/SalesTrackingCategories/0: extraneous key [TrackingOptionName] is not permitted

### ISSUE THREAD

**Issue by smcleodau** [singer-io/tap-xero#23]
Error persisting data for table "contacts": Record 1389 did not conform to schema:
#: #: no subschema matched out of the total 2 subschemas
#: expected: null, found: JSONObject
#/SalesTrackingCategories: #: no subschema matched out of the total 2 subschemas
#/SalesTrackingCategories: expected: null, found: JSONArray
#/SalesTrackingCategories/0: #: no subschema matched out of the total 2 subschemas
#/SalesTrackingCategories/0: expected: null, found: JSONObject
#/SalesTrackingCategories/0: 2 schema violations found
#/SalesTrackingCategories/0: extraneous key [TrackingOptionName] is not permitted
#/SalesTrackingCategories/0: extraneous key [TrackingCategoryName] is not permitted
[100518-69022-1517450040.zip](https://github.com/singer-io/tap-xero/files/1684030/100518-69022-1517450040.zip)

**Comment by nick-mccoy** [comment]
Thanks for catching this, we are looking into it and it should be resolved within the coming week.

**Comment by smcleodau** [comment]
Thank you.

**Comment by sminnee** [comment]
This was fixed in 8db6bf2a0d013121f4ebd5b9b600a8142c461c8f.

**Comment by dmosorast** [comment]
:+1: Closing this issue.
