### ISSUE TITLE
Error persisting data for table "invoices": Record 381 did not conform to schema:

### ISSUE THREAD

**Issue by MatrixAlain** [singer-io/tap-xero#42]
`INFO Running tap-xero version 0.1.23 and target-stitch version 1.7.0`

Error persisting data for table "invoices": Record 381 did not conform to schema:
#: #: no subschema matched out of the total 2 subschemas
#: expected: null, found: JSONObject
#/Prepayments: #: no subschema matched out of the total 2 subschemas
#/Prepayments: expected: null, found: JSONArray
#/Prepayments/0: #: no subschema matched out of the total 2 subschemas
#/Prepayments/0: expected: null, found: JSONObject
#/Prepayments/0: 2 schema violations found
#/Prepayments/0: extraneous key [ID] is not permitted
#/Prepayments/0: extraneous key [AppliedAmount] is not permitted

**Comment by sminnee** [comment]
My suspicion is that https://github.com/singer-io/tap-xero/blob/master/tap_xero/schemas/allocations.json is out of sync with https://developer.xero.com/documentation/api/prepayments
