### ISSUE TITLE
Error persisting data for table "manual_journals": Record 0 did not conform to schema

### ISSUE THREAD

**Issue by dylan-stitch** [singer-io/tap-xero#56]
This occurred in the Stitch production environment running tap-xero version 0.1.29

Error persisting data for table "manual_journals": Record 0 did not conform to schema:
-: #: no subschema matched out of the total 2 subschemas
-: expected: null, found: JSONObject
-/JournalLines: #: no subschema matched out of the total 2 subschemas
-/JournalLines: expected: null, found: JSONArray
-/JournalLines: 4 schema violations found
-/JournalLines/0: #: no subschema matched out of the total 2 subschemas
-/JournalLines/0: expected: null, found: JSONObject
-/JournalLines/0: extraneous key [AccountID] is not permitted
-/JournalLines/1: #: no subschema matched out of the total 2 subschemas
-/JournalLines/1: expected: null, found: JSONObject
-/JournalLines/1: extraneous key [AccountID] is not permitted

**Comment by KAllan357** [comment]
Looks like AccountId is a valid field on this schema and is coming back in the data we are retrieving. Likely resolved by adding additional schema at this level - https://github.com/singer-io/tap-xero/blob/master/tap_xero/schemas/manual_journals.json#L43

**Comment by sminnee** [comment]
I'm also seeing this, so I guess it's a common issue.

**Comment by sminnee** [comment]
As a general comment, your current architecture makes this tap very brittle against Xero API changes. Perahps extraneous keys should surface a warning/notice rather than a full error?
