### ISSUE TITLE
Import archived contacts

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-xero#59]
Xero Contacts import has an includeArchived=true option. In many cases (building a clone of your Xero data structure in your data warehouse) pulling through archived contacts will be quite important.

Can we either change the default behaviour to include archived contacts, or failing that have this as an option that is also exposed on the StitchData UI?

**Comment by sminnee** [comment]
Presumably PaginatedStream would require new constructor argument to pass in additional filter_options here:
https://github.com/singer-io/tap-xero/blob/master/tap_xero/streams.py#L91

Which could then be passed here:
https://github.com/singer-io/tap-xero/blob/master/tap_xero/streams.py#L177

Given that there is already filtering by "since" that can let users of this integration ignore older contacts, would it make sense to enable includeArchived=true for all users?

**Comment by sminnee** [comment]
@b-ryan @KAllan357 if I made a PR for this, would it be likely to get merged?

**Comment by KAllan357** [comment]
@sminnee apologies for not seeing this. Yes, I'd merge this change. I agree with what you mentioned above and I think it should just be the default behavior - no need for an option.

**Comment by prijendev** [comment]
@sminnee  This change is already merged. ([link](https://github.com/singer-io/tap-xero/pull/84)). So, can we close this issue?
