### ISSUE TITLE
Account Code format error

### ISSUE THREAD

**Issue by sminnee** [singer-io/tap-xero#69]
The Code field of Account has started being misinterpreted as a date.

For example:

Was: `272`

Now: `0272-10-27T00:00:00.000000Z`

The value is still being saved into a string field in the database, though.

**Comment by sminnee** [comment]
This also affects credit_note, invoice and so essentially corrupts the data import.

**Comment by briansloane** [comment]
Our team is working on a PR to fix this here: https://github.com/singer-io/tap-xero/pull/70

**Comment by sminnee** [comment]
Thanks @briansloane!

**Comment by briansloane** [comment]
@sminnee The PR has been merged. Please try it out and see if it has resolved the issue.

**Comment by sminnee** [comment]
Will do. I normally use it via StitchData; will you be pushing a 2.0.1 soon or did you want me to test first?

**Comment by sminnee** [comment]
Hi there — I have confirmed that this works! 🎉 

I look forward to a 2.0.1 release on the StitchData servers 😄 🙏

**Comment by dmosorast** [comment]
Looks like this has been released in 2.0.1, closing this issue.

**Comment by sminnee** [comment]
Thanks, I'm doing a resync on stitchdata now; I'll raise a new ticket if I see any other issues.
